# Basic apps
windowrule = tile on, match:class ^(librewolf)$
windowrule = float on, match:class ^(pavucontrol)$
windowrule = float on, match:class ^(blueman-manager)$
windowrule = float on, match:class ^(nm-connection-editor)$
windowrule = float on, match:class ^(mpv)$
windowrule = float on, match:class ^(swayimg)$

windowrule = float on, match:title ^(Picture-in-Picture)$
windowrule = pin on, match:title ^(Picture-in-Picture)$
windowrule = move 69.5% 4%, match:title ^(Picture-in-Picture)$
windowrule = float on, match:title ^(Friends List)$
windowrule = float on, match:title ^(Save Image - *)$

# Pavucontrol floating
windowrule = float on, match:class (.*org.pulseaudio.pavucontrol.*)
windowrule = size 700 600, match:class (.*org.pulseaudio.pavucontrol.*)
windowrule = center on, match:class (.*org.pulseaudio.pavucontrol.*)
windowrule = pin on, match:class (.*org.pulseaudio.pavucontrol.*)

# Hyprland Share Picker
windowrule = float on,  match:class (hyprland-share-picker)
windowrule = pin on,  match:class (hyprland-share-picker)
windowrule = center on, match:title (hyprland-share-picker)
windowrule = size 600 400, match:class (hyprland-share-picker)

# Games
windowrule = tile on, match:title ^(ZenlessZoneZero)$
windowrule = move -1000 -1000, match:class ^(steam_app_default)$, match:title ^$
windowrule = tile on, match:title ^(Wuthering Waves)$
windowrule = fullscreen on, match:title ^(osu!)$

# Screenlock
windowrule = idle_inhibit always, match:content 2
windowrule = idle_inhibit always, match:content 3
windowrule = idle_inhibit always, match:fullscreen_state_client 2
windowrule = idle_inhibit always, match:fullscreen_state_internal 2

# Hypr Plugin Manager
windowrule = darkwindow:shade chromakey bkg=[0.122 0.039 0.137] similarity=0.3 targetOpacity=0.9, match:class ^(org.telegram.desktop)$
windowrule = darkwindow:shade chromakey bkg=[0.11 0.122 0.133] similarity=0.3 targetOpacity=0.9, match:class ^(org.openrgb.OpenRGB)$
windowrule = darkwindow:shade chromakey bkg=[0.176 0.2 0.235] similarity=0.3 targetOpacity=0.9, match:class ^(steam)$
windowrule = darkwindow:shade chromakey bkg=[0.125 0.137 0.149] similarity=0.3 targetOpacity=0.9, match:class ^(org.kde.dolphin)$

# # General floating
# windowrule = float on, match:class (dotfiles-floating)
# windowrule = size 1000 700, match:class (dotfiles-floating)
# windowrule = center on, match:class (dotfiles-floating)
# windowrule = pin on,  match:class (dotfiles-floating)
