# ----------------------------------------------------- 
# General window decoration
# name: "Default"
# ----------------------------------------------------- 

general {
    border_size = 2
        col.inactive_border = rgba(d50000ff) rgba(c300afff) 90deg
        col.active_border = rgba(9a00ffff) rgba(de00e7ff) 90deg
}

decoration {
    rounding = 10
        rounding_power = 2
        blur {
            enabled = true
                size = 2
                passes = 4
                new_optimizations = on
                ignore_opacity = true
                contrast = 1.0
                brightness = 1.0
                vibrancy = 0.5
                vibrancy_darkness = 0.1
                xray = false
                noise = 0
                popups = true
                input_methods = true
        }
    active_opacity = 1.0
        inactive_opacity = 1.0
        dim_inactive = true
        dim_strength = 0.0
        fullscreen_opacity = 1.0

        shadow {
            enabled = true
                range = 100
                render_power = 4
                color = 0x66000000
                color_inactive = 0x33000000
                offset = 0, 10
                scale = 1
        }
}

windowrule = nodim 1, fullscreenstate:* 2
