source = /home/inorishio/.config/hypr/effects/colors/colors.conf

general {

}

background {
    monitor =
    path = /home/inorishio/Pictures/Backgrounds/128063483_p0.png
    blur_size = 4
    blur_passes = 3 # 0 disables blurring
    noise = 0.0117
    contrast = 1
    brightness = 1
    vibrancy = 0.0
    vibrancy_darkness = 0.0
}

# Hours
label {
    monitor =
    text = cmd[update:1000] echo "<b><big> $(date +"%H") </big></b>"
    color = $vivian2
    font_size = 112
    font_family = Geist Mono 10
    shadow_passes = 3
    shadow_size = 4

    position = 0, 400
    halign = center
    valign = center
}

# Minutes
label {
    monitor =
    text = cmd[update:1000] echo "<b><big> $(date +"%M") </big></b>"
    color = $vivian2
    font_size = 112
    font_family = Geist Mono 10
    shadow_passes = 3
    shadow_size = 4

    position = 0, 270
    halign = center
    valign = center
}

# Today
label {
    monitor =
    text = cmd[update:18000000] echo "<b><big> "$(date +'%A')" </big></b>"
    color = $vivian2
    font_size = 22
    font_family = JetBrainsMono Nerd Font 10

    position = 0, 180
    halign = center
    valign = center
}

# Week
label {
    monitor =
    text = cmd[update:18000000] echo "<b> "$(date +'%d %b')" </b>"
    color = $vivian2
    font_size = 18
    font_family = JetBrainsMono Nerd Font 10

    position = 0, 155
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 3

    dots_size = 0.26 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.64 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    dots_rounding = -1

    rounding = 22
    outer_color = $vivian2
    inner_color = $vivian2
    font_color = $vivian1
    fade_on_empty = true
    placeholder_text = <i>Password...</i> # Text rendered in the input box when it's empty.

    position = 0, 120
    halign = center
    valign = bottom
}
