# QT 
layerrule = blur on, match:namespace ZShell-Notifs
layerrule = blur_popups on, match:namespace ZShell-Notifs
layerrule = ignore_alpha 0.5, match:namespace ZShell-Notifs

layerrule = blur on, match:namespace ZShell-Bar
layerrule = blur_popups on, match:namespace ZShell-Bar
layerrule = ignore_alpha 0.5, match:namespace ZShell-Bar

layerrule = blur on, match:namespace ZShell-Bar-Exclusion
layerrule = blur_popups on, match:namespace ZShell-Bar-Exclusion
layerrule = ignore_alpha 0.5, match:namespace ZShell-Bar-Exclusion

layerrule = blur on, match:namespace ZShell-Wallpaper
layerrule = blur_popups on, match:namespace ZShell-Wallpaper
layerrule = ignore_alpha 0.5, match:namespace ZShell-Wallpaper

layerrule = blur on, match:namespace ZShell-Launcher
layerrule = blur_popups on, match:namespace ZShell-Launcher
layerrule = ignore_alpha 0.5, match:namespace ZShell-Launcher

layerrule = blur on, match:namespace ZShell-Auth
layerrule = blur_popups on, match:namespace ZShell-Auth
layerrule = ignore_alpha 0.5, match:namespace ZShell-Auth

layerrule = blur on, match:namespace IDeskPet-Pet
layerrule = blur_popups on, match:namespace IDeskPet-Pet
layerrule = ignore_alpha 0.5, match:namespace IDeskPet-Pet
