# exec-once = uwsm app -S out -- ~/.config/hypr/scripts/Workspace_Wallpapers.sh
# exec-once = uwsm app -S out -- ~/.config/hypr/scripts/Stream.sh
# exec-once = uwsm app -S out -- ~/.config/hypr/scripts/Z-Cast.sh
# exec-once = uwsm app -S out -- ~/.config/hypr/scripts/OBS.sh
exec-once = uwsm app -S out -- ~/.config/hypr/scripts/Gtk-Settings.sh 
